# https://github.com/marco-lancini/docker_burp/blob/master/docker-compose.yml
# https://www.marcolancini.it/2018/blog-docker-burp/
version: '2'

services:
    burp:
        container_name: burp
        build: burp/
        ports:
            - "8080:8080"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./_data/:/home/tester/
        environment:
            DISPLAY: ${LOCAL_IP}:0
        command: java -jar -Xmx1024m /home/tester/sources/burp_pro.jar